"""followers relationship

Revision ID: 540a14c0166a
Revises: abe056d8b39c
Create Date: 2020-04-14 12:48:10.692671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '540a14c0166a'
down_revision = 'abe056d8b39c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
